### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by cnetboy** [KirigiriSuzumiya/crowd_vis#1]
(crowd_vis) mosaic@mosaic-virtual-machine:~/Public/crowd_vis$ 
(crowd_vis) mosaic@mosaic-virtual-machine:~/Public/crowd_vis$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

python /home/mosaic/Public/crowd_vis/pp-human/pipeline/pipeline.py --config /home/mosaic/Public/crowd_vis/pp-human/pipeline/config/infer_cfg_pphuman.yml  --video_file=/home/mosaic/Public/crowd_vis/test1.mp4 --run_mode=openvino --output_dir=output --do_entrance_counting --show_id=1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mosaic/Public/crowd_vis/crowd_vis/views.py", line 32, in pp_human_service
    subprocess.run(shell)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python /home/mosaic/Public/crowd_vis/pp-human/pipeline/pipeline.py --config /home/mosaic/Public/crowd_vis/pp-human/pipeline/config/infer_cfg_pphuman.yml  --video_file=/home/mosaic/Public/crowd_vis/test1.mp4 --run_mode=openvino --output_dir=output --do_entrance_counting --show_id=1': 'python /home/mosaic/Public/crowd_vis/pp-human/pipeline/pipeline.py --config /home/mosaic/Public/crowd_vis/pp-human/pipeline/config/infer_cfg_pphuman.yml  --video_file=/home/mosaic/Public/crowd_vis/test1.mp4 --run_mode=openvino --output_dir=output --do_entrance_counting --show_id=1'

System check identified no issues (0 silenced).
December 31, 2022 - 15:07:18
Django version 3.2.16, using settings 'crowd_vis.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[31/Dec/2022 15:07:47] "GET / HTTP/1.1" 200 49167
[31/Dec/2022 15:07:47] "GET /static/css/index01.css HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/css/index.css HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/css/BigData.css HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/bstable/css/bootstrap.min.css HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/css/Security_operation.css HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/Home_page.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/jquery.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/laydate.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/artDialog/skins/default.css HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/index.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/bstable/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/jquery.pagination.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/bstable/js/bootstrap.min.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/bstable/css/bootstrap-table.css HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/bstable/js/bootstrap-table.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/artDialog/artDialog.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/echarts-all.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/video/img.png HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/js/artDialog/plugins/iframeTools.source.js HTTP/1.1" 304 0
[31/Dec/2022 15:07:47] "GET /static/video/video.jpg HTTP/1.1" 304 0

**Comment by KirigiriSuzumiya** [comment]
linux上跑的话加一个shell=True。已经改在[[e506423](https://github.com/KirigiriSuzumiya/crowd_vis/commit/e50642329fcba29f588c899c0e36123e8403480f)]里了
