### ISSUE TITLE
你好！我进入网站显示不了视频，以下是报错

### ISSUE THREAD

**Issue by zhelishisongjie** [KirigiriSuzumiya/crowd_vis#3]
[16/Mar/2023 10:26:03] "GET /num_count HTTP/1.1" 200 4
Internal Server Error: /graph_vis
Traceback (most recent call last):
  File "C:\Anaconda3\envs\PP\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Anaconda3\envs\PP\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\crowd_vis\crowd_vis\views.py", line 184, in graph_vis
    .add('', pie_data, center=['50%', '60%'], radius='70%')
  File "C:\Anaconda3\envs\PP\lib\site-packages\pyecharts\charts\basic_charts\pie.py", line 49, in add
    elif isinstance(data_pair[0], opts.PieItem):
IndexError: list index out of range
[16/Mar/2023 10:26:03] "GET /graph_vis HTTP/1.1" 500 92862
[16/Mar/2023 10:26:04] "GET /num_count HTTP/1.1" 200 4
[OpenVINO]pp-human/pipeline/model/picodet_v2_s_320_pedestrian\model.pdmodel infer request created
video fps: 0, frame_count: 0
[16/Mar/2023 10:26:12] "GET /num_count HTTP/1.1" 200 4
Thread: 0; frame id: 0
Internal Server Error: /graph_vis
Traceback (most recent call last):
  File "C:\Anaconda3\envs\PP\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Anaconda3\envs\PP\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\crowd_vis\crowd_vis\views.py", line 184, in graph_vis
    .add('', pie_data, center=['50%', '60%'], radius='70%')
  File "C:\Anaconda3\envs\PP\lib\site-packages\pyecharts\charts\basic_charts\pie.py", line 49, in add
    elif isinstance(data_pair[0], opts.PieItem):
IndexError: list index out of rangesave result to output\test1.mp4

**Comment by zhelishisongjie** [comment]
我该怎么解决呢？

**Comment by KirigiriSuzumiya** [comment]
可以拉取一下最新的更新，我进行了修复

**Comment by zhelishisongjie** [comment]
谢谢！拉取更新后能够正常运行了！但是当我打开跌倒检测时（将SKELETON_ACTION:enable=True），又出现了新的报错无法显示视频：
OpenVINO Runtime Core Created!
Multi-Object Tracking enabled
SkeletonAction Recognition enabled
DET  model dir:  pp-human/pipeline/model/picodet_v2_s_320_pedestrian
MOT  model dir:  pp-human/pipeline/model/picodet_v2_s_320_pedestrian
KPT  model dir:  pp-human/pipeline/model/tinypose_256x192
SKELETON_ACTION  model dir:  C:\Users\admin/.cache/paddle/infer_weights\STGCN
-----------  Model Configuration -----------
Model Arch: STGCN
Transform Order:
--transform op: AutoPadding
--------------------------------------------
[OpenVINO]C:\Users\admin/.cache/paddle/infer_weights\STGCN\model.pdmodel infer request created
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order:
--transform op: TopDownEvalAffine
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
[OpenVINO]pp-human/pipeline/model/tinypose_256x192\model.pdmodel infer request created
-----------  Model Configuration -----------
Model Arch: PicoDet
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
[OpenVINO]pp-human/pipeline/model/picodet_v2_s_320_pedestrian\model.pdmodel infer request created
video fps: 24, frame_count: 1023
Thread: 0; frame id: 0
Thread: 0; trackid number: 1
[17/Mar/2023 08:49:24] "GET / HTTP/1.1" 200 49167
[17/Mar/2023 08:49:24] "GET /static/css/index.css HTTP/1.1" 200 9806
[17/Mar/2023 08:49:24] "GET /static/css/index01.css HTTP/1.1" 200 4558
[17/Mar/2023 08:49:24] "GET /static/js/artDialog/skins/default.css HTTP/1.1" 200 6901
[17/Mar/2023 08:49:24] "GET /static/css/BigData.css HTTP/1.1" 200 8321
[17/Mar/2023 08:49:24] "GET /static/js/laydate.js HTTP/1.1" 200 13766
[17/Mar/2023 08:49:24] "GET /static/js/jquery.js HTTP/1.1" 200 284394
[17/Mar/2023 08:49:24] "GET /static/js/bstable/css/bootstrap-table.css HTTP/1.1" 200 6968
[17/Mar/2023 08:49:24] "GET /static/js/bstable/css/bootstrap.min.css HTTP/1.1" 200 122540
[17/Mar/2023 08:49:24] "GET /static/js/Home_page.js HTTP/1.1" 200 2058
[17/Mar/2023 08:49:24] "GET /static/css/Security_operation.css HTTP/1.1" 200 16916
[17/Mar/2023 08:49:25] "GET /static/js/echarts-all.js HTTP/1.1" 200 972410
[17/Mar/2023 08:49:25] "GET /static/js/index.js HTTP/1.1" 200 117281
[17/Mar/2023 08:49:25] "GET /static/js/need/laydate.css HTTP/1.1" 200 5883
[17/Mar/2023 08:49:25] "GET /static/js/skins/default/laydate.css HTTP/1.1" 200 3507
[17/Mar/2023 08:49:25] "GET /static/js/bstable/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 200 853
[17/Mar/2023 08:49:25] "GET /static/js/jquery.pagination.js HTTP/1.1" 200 3066
[17/Mar/2023 08:49:25] "GET /static/js/bstable/js/bootstrap.min.js HTTP/1.1" 200 35951
[17/Mar/2023 08:49:25] "GET /static/js/bstable/js/bootstrap-table.js HTTP/1.1" 200 100271
[17/Mar/2023 08:49:25] "GET /static/video/img.png HTTP/1.1" 200 176855
[17/Mar/2023 08:49:25] "GET /static/js/artDialog/artDialog.js HTTP/1.1" 200 34967
[17/Mar/2023 08:49:25] "GET /static/video/video.jpg HTTP/1.1" 200 141040
[17/Mar/2023 08:49:25] "GET /static/img/bg01.png HTTP/1.1" 200 743920
[17/Mar/2023 08:49:25] "GET /static/js/artDialog/plugins/iframeTools.source.js HTTP/1.1" 200 11562
[17/Mar/2023 08:49:25] "GET /static/img/pushmessage_class.png HTTP/1.1" 200 3398
[17/Mar/2023 08:49:25] "GET /static/img/pushmessage_localize_01.png HTTP/1.1" 200 1311
[17/Mar/2023 08:49:25] "GET /static/img/first_title.png HTTP/1.1" 200 17373
[17/Mar/2023 08:49:25] "GET /static/img/pushmessage_level01.png HTTP/1.1" 200 1982
[17/Mar/2023 08:49:25] "GET /static/img/data_bg.png HTTP/1.1" 200 1924
[17/Mar/2023 08:49:25] "GET /static/fonts/data_Number.ttf HTTP/1.1" 200 33940
Not Found: /img/second_title.png
[17/Mar/2023 08:49:25] "GET /img/second_title.png HTTP/1.1" 404 3008
[17/Mar/2023 08:49:26] "GET /static/js/skins/danlan/laydate.css HTTP/1.1" 200 3360
[17/Mar/2023 08:49:27] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:28] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:29] "GET /num_count HTTP/1.1" 200 4
Not Found: /favicon.ico
[17/Mar/2023 08:49:29] "GET /favicon.ico HTTP/1.1" 404 2981
[17/Mar/2023 08:49:29] "GET /static/js/artDialog/skins/icons/loading.gif HTTP/1.1" 200 381
[17/Mar/2023 08:49:29] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:29] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:31] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:31] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:32] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:33] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:34] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:35] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:36] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:37] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:37] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:39] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:39] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:42] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:42] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:44] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:44] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:47] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:47] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:49] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:50] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:52] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:52] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:54] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:54] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:56] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:49:57] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:49:58] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:00] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:01] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:02] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:05] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:09] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:12] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:14] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:16] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:18] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:19] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:25] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:26] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:28] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:28] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:29] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:29] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:31] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:31] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:34] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:34] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:35] "GET /num_count HTTP/1.1" 200 4
[17/Mar/2023 08:50:36] "GET /graph_vis HTTP/1.1" 200 14714
[17/Mar/2023 08:50:38] "GET /num_count HTTP/1.1" 200 4

还有我该怎么做才能调用摄像头呢？

**Comment by KirigiriSuzumiya** [comment]
你发的log里面没有任何报错，我不知道你遇到了什么问题。不使用视频的话可以修改views.py中的FLAGS变量
